# Generated by Django 3.2.8 on 2021-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dataset'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
